server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cnp-service
          uri: lb://cnp-service
          predicates:
            - Path=/cnp/**
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/product/**
